services:
  mongo:
    image: mongo:latest
    restart: always
    command: "--logpath=/dev/null"
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: sails
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
