services:
  mongo:
    image: mongo
    restart: always
    container_name: mongoDb
    environment:
      MONGO_INITDB_DATABASE: chat
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mySecretPasswordYouSee
    ports:
      - 5000:27017
    volumes:
      - ./mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongoGui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mySecretPasswordYouSee
      ME_CONFIG_MONGODB_URL: mongodb://root:mySecretPasswordYouSee@mongo:27017/

