services:
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    ports:
      - "3306:3306" 
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: social-network

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080

